name: Upload Release Artifacts

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: microsoft
          java-version: 21
      - name: Make Gradle executable
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Upload GitHub Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release upload ${{ github.ref_name }} build/libs/Dynamite.jar &
      - name: Create Diruptio projects version (pre-release)
        if: 'github.event.release.prerelease'
        run: |
          curl -X POST -H "Content-Type: application/json" -H "Authorization: ${{ secrets.AUTHORIZATION_HEADER }}" -d "{"project":"dynamite","name":"${{ github.ref_name }}","tags":["pre-release"],"gitCommit":"${{ github.sha }}"}" "https://api.diruptio.de/project/version/create"
      - name: Create Diruptio projects version (release)
        if: '!github.event.release.prerelease'
        run: |
          curl -X POST -H "Content-Type: application/json" -H "Authorization: ${{ secrets.AUTHORIZATION_HEADER }}" -d "{"project":"dynamite","name":"${{ github.ref_name }}","tags":["release"],"gitCommit":"${{ github.sha }}"}" "https://api.diruptio.de/project/version/create"
      - name: Upload to Diruptio projects
        run: |
          cat build/libs/Dynamite.jar | curl -X GET -H "Authorization: ${{ secrets.AUTHORIZATION_HEADER }}" --data @- "https://api.diruptio.de/project/version/upload?project=dynamite&version=${{ github.ref_name }}&file=Dynamite.jar"